name: Build and deploy

on:
  workflow_run:
    workflows: ["Check and test"]
    branches: [main]
    types:
      - completed
  release:
    types:
      - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          make image
#      - name: Docker Build and Push
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          dockerfile: docker/Dockerfile
#          registry: us.gcr.io/playground-243019
#          tag_with_ref: true
#          push: true
#          build_args: GITHUB_ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}
