name: Check and test

# This workflow will run on master branch and on any pull requests targeting master
on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: Check out code
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Lint Go Code
        run: |
          make check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: Check out code
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Run Unit tests.
        run: |
          make test

      # - name: Upload Coverage report to CodeCov
      #   uses: codecov/codecov-action@v1.0.0
      #   with:
      #     token: ${{secrets.CODECOV_TOKEN}}
      #     file: ./coverage.txt
